repos:
  - repo: local
    hooks:
      - id: dependency-check
        name: Dependency Check
        entry: dependency-check
        language: system
        types: [python]
        args: ['--scan', '.']

  # Basic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Git secrets for sensitive data
  - repo: https://github.com/awslabs/git-secrets.git
    rev: master
    hooks:
      - id: git-secrets
        args: ["--aws-provider"]

  # Security check from security-git-hooks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
