repos:
  - repo: local
    hooks:
      - id: threat-mitigation
        name: Validate Threat Mitigation
        entry: python3 threatmodelgit.py
        language: python
        stages: [pre-commit]
